[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

# 五大区 + 澳门
emoji=(香港|广港|HK|HKG|Hong Kong),🇭🇰
emoji=(澳门|MO|Macao|Macau),🇲🇴
emoji=(台湾|TW|TWN|Taiwan),🇨🇳
emoji=(新加坡|狮城|SG|SGP|Singapore),🇸🇬
emoji=(日本|沪日|JP|JPN|Japan),🇯🇵
emoji=(美国|US|USA|United States),🇺🇸
# 欧洲
emoji=(白俄罗斯),🇧🇾
emoji=(俄罗斯|莫斯科|圣彼得堡|RUS|Russia|Moscow|Petersburg),🇷🇺
emoji=(爱沙尼亚),🇪🇪
emoji=(拉脱维亚),🇱🇻
emoji=(立陶宛|Lithuania),🇱🇹
emoji=(波兰|Poland),🇵🇱
emoji=(乌克兰|Ukraine),🇺🇦
emoji=(摩尔多瓦|Moldova),🇲🇩
emoji=(冰岛|Iceland),🇮🇸
emoji=(爱尔兰|Ireland|Irish),🇮🇪
emoji=(马恩岛|曼岛),🇮🇲
emoji=(英国|伦敦|UK|United Kingdom|Britain|London|Coventry),🇬🇧
emoji=(法国|FR|France|Paris),🇫🇷
emoji=(摩纳哥),🇲🇨
emoji=(德国|DE|Germany|Berlin),🇩🇪
emoji=(捷克|Czech),🇨🇿
emoji=(斯洛伐克),🇸🇰
emoji=(法罗群岛),🇫🇴
emoji=(丹麦|Denmark),🇩🇰
emoji=(挪威|Norway),🇳🇴
emoji=(瑞典|Sweden),🇸🇪
emoji=(奥兰|奥兰群岛),🇦🇽
emoji=(芬兰|Finland),🇫🇮
emoji=(荷兰|Holland|Netherlands),🇳🇱
emoji=(比利时|Belgium),🇧🇪
emoji=(卢森堡|Luxembourg),🇱🇺
emoji=(安道尔|Andorra),🇦🇩
emoji=(直布罗陀),🇬🇮
emoji=(西班牙|Spain|España|Euskaltel),🇪🇸
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(瑞士|Switzerland),🇨🇭
emoji=(列支敦士登|Liechtenstein),🇱🇮
emoji=(奥地利|维也纳|AT|Austria|Austrian|Vienna),🇦🇹
emoji=(匈牙利|Hungary),🇭🇺
emoji=(意大利|Italy|Italia|Rome),🇮🇹
emoji=(梵蒂冈),🇻🇦
emoji=(圣马力诺),🇸🇲
emoji=(克罗地亚),🇭🇷
emoji=(斯洛文尼亚),🇸🇮
emoji=(波黑|波斯尼亚),🇧🇦
emoji=(黑山),🇲🇪
emoji=(阿尔巴尼亚|Albania),🇦🇱
emoji=(塞尔维亚),🇷🇸
emoji=(北马其顿),🇲🇰
emoji=(希腊|Greece),🇬🇷
emoji=(罗马尼亚|Romania),🇷🇴
emoji=(保加利亚|Bulgaria),🇧🇬
emoji=(马耳他),🇲🇹
# 亚洲
emoji=(蒙古|Mongolia),🇲🇳
emoji=(朝鲜|North Korea),🇰🇵
emoji=(韩国|韩|KR|Korea|KOR|South Korea),🇰🇷
emoji=(不丹|Bhutan),🇧🇹
emoji=(尼泊尔|Nepal),🇳🇵
emoji=(孟加拉国|孟加拉|Bangladesh),🇧🇩
emoji=(马尔代夫|Maldives),🇲🇻
emoji=(斯里兰卡|Sri Lanka),🇱🇰
emoji=(印度|IN|IND|India),🇮🇳
emoji=(印度尼西亚|印尼|ID|IDN|Indonesia),🇮🇩
emoji=(马来西亚|Malaysia),🇲🇾
emoji=(菲律宾|PH|Philippines),🇵🇭
emoji=(文莱|Brunei),🇧🇳
emoji=(东帝汶|Timor-Leste),🇹🇱
emoji=(越南|Vietnam),🇻🇳
emoji=(缅甸|Myanmar),🇲🇲
emoji=(老挝|Laos),🇱🇦
emoji=(柬埔寨|Cambodia),🇰🇭
emoji=(泰国|Thailand),🇹🇭
emoji=(哈萨克斯坦|Kazakhstan),🇰🇿
emoji=(吉尔吉斯斯坦|Kyrgyzstan),🇰🇬
emoji=(塔吉克斯坦|Tajikistan),🇹🇯
emoji=(乌兹别克斯坦|Uzbekistan),🇺🇿
emoji=(土库曼斯坦|Turkmenistan),🇹🇲
emoji=(巴基斯坦|Pakistan),🇵🇰
emoji=(阿富汗|Afghanistan),🇦🇫
emoji=(阿拉伯联合酋长国|阿联酋|迪拜|Dubai),🇦🇪
emoji=(沙特阿拉伯|沙特|Saudi Arabia),🇸🇦
emoji=(也门|Yemen),🇾🇪
emoji=(巴林|Bahrain),🇧🇭
emoji=(卡塔尔|Qatar),🇶🇦
emoji=(阿曼|Oman),🇴🇲
emoji=(塞浦路斯),🇨🇾
emoji=(土耳其|TR|Turkey|Türkiye),🇹🇷
emoji=(格鲁吉亚|Georgia),🇬🇪
emoji=(亚美尼亚|Armenia),🇦🇲
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(伊朗|Iran),🇮🇷
emoji=(伊拉克|Iraq),🇮🇶
emoji=(科威特|Kuwait),🇰🇼
emoji=(以色列|Israel),🇮🇱
emoji=(巴勒斯坦|Palestine),🇵🇸
emoji=(约旦|Jordan),🇯🇴
emoji=(黎巴嫩|Lebanon),🇱🇧
emoji=(叙利亚|Syria),🇸🇾
# 非洲
emoji=(埃及|Egypt),🇪🇬
emoji=(苏丹),🇸🇩
emoji=(佛得角),🇨🇻
emoji=(摩洛哥),🇲🇦
emoji=(突尼斯),🇹🇳
emoji=(阿尔及利亚),🇩🇿
emoji=(利比亚),🇱🇾
emoji=(肯尼亚),🇰🇪
emoji=(卢旺达),🇷🇼
emoji=(布隆迪),🇧🇮
emoji=(马里),🇲🇱
emoji=(塞内加尔),🇸🇳
emoji=(科特迪瓦),🇨🇮
emoji=(加纳),🇬🇭
emoji=(多哥),🇹🇬
emoji=(贝宁),🇧🇯
emoji=(尼日利亚|Nigeria),🇳🇬
emoji=(刚果（金）|刚果民主共和国),🇨🇩
emoji=(喀麦隆),🇨🇲
emoji=(赤道几内亚),🇬🇶
emoji=(安哥拉),🇦🇴
emoji=(坦桑尼亚),🇹🇿
emoji=(莫桑比克),🇲🇿
emoji=(津巴布韦),🇿🇼
emoji=(斯威士兰),🇸🇿
emoji=(南非|South Africa),🇿🇦
emoji=(马达加斯加),🇲🇬
emoji=(留尼汪|法属留尼汪),🇷🇪
emoji=(毛里求斯),🇲🇺
# 大洋洲
emoji=(澳大利亚|澳洲|悉尼|墨尔本|AU|Australia),🇦🇺
emoji=(新西兰|New Zealand),🇳🇿
emoji=(所罗门群岛),🇸🇧
emoji=(关岛),🇬🇺
emoji=(斐济),🇫🇯
emoji=(汤加),🇹🇴
emoji=(巴布亚新几内亚),🇵🇬
# 北美洲
emoji=(百慕大),🇧🇲
emoji=(格陵兰岛|格陵兰),🇬🇱
emoji=(加拿大|CA|Canada),🇨🇦
emoji=(墨西哥|MX|Mexico),🇲🇽
emoji=(伯利兹),🇧🇿
emoji=(危地马拉),🇬🇹
emoji=(萨尔瓦多),🇸🇻
emoji=(洪都拉斯),🇭🇳
emoji=(尼加拉瓜),🇳🇮
emoji=(哥斯达黎加),🇨🇷
emoji=(巴拿马),🇵🇦
# 加勒比海周围的海上国家属于北美
emoji=(巴哈马),🇧🇸
emoji=(古巴),🇨🇺
emoji=(牙买加),🇯🇲
emoji=(海地),🇭🇹
emoji=(波多黎各),🇵🇷
emoji=(多米尼加),🇩🇴
emoji=(多米尼克),🇩🇲
emoji=(马提尼克),🇲🇶
emoji=(巴巴多斯),🇧🇧
emoji=(英属维尔京|英属维尔京群岛),🇻🇬
emoji=(开曼群岛),🇰🇾
emoji=(荷属库拉索|库拉索),🇨🇼
emoji=(特立尼达和多巴哥),🇹🇹
emoji=(阿鲁巴),🇦🇼
emoji=(瓜德罗普),🇬🇵
emoji=(安提瓜和巴布达),🇦🇬
# 南美洲
emoji=(巴西|BR|Brazil),🇧🇷
emoji=(阿根廷|AR|Argentina),🇦🇷
emoji=(巴拉圭),🇵🇾
emoji=(乌拉圭),🇺🇾
emoji=(苏里南),🇸🇷
emoji=(圭亚那),🇬🇾
emoji=(法属圭亚那),🇬🇫
emoji=(委内瑞拉),🇻🇪
emoji=(哥伦比亚|Colombia),🇨🇴
emoji=(厄瓜多尔),🇪🇨
emoji=(玻利维亚),🇧🇴
emoji=(秘鲁|Peru),🇵🇪
emoji=(智利|Chile),🇨🇱
# 南极洲
emoji=(南极|Antarctica),🇦🇶

# icon
# 🚀✈️♻️🌍🌎🌏🎯🐳🐟
# 🤖🔍🌐📲🍎Ⓜ️🧩🎬📺🎥🎮🕹️🐟⛔️🔴🔵
# 🎧🎵🎶🖥📽📹📟🎹🍭🍡🎃🎁📮🧲📬📭
# ⭐☀️🌟⚡️🔥💧❄️🌈🥊💎🔮🐹📍🥇🥈🥉

[clash_set]
; 核心注入：强制让转换器在生成 Clash 节点列表时，为所有节点注入 udp: true
udp = true

;设置规则标志位
;ruleset=🛑 QUIC拦截,https://raw.githubusercontent.com/xiaoqin24/ACL4SSR-ClashConfig/refs/heads/rm/DropQUIC.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Binance.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/uki0xc/ukix/refs/heads/main/Rule/Binance.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/StricklandF/Filter/refs/heads/main/Binance.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Binance/Binance.list
ruleset=💰 币安交易所,https://raw.githubusercontent.com/powerfullz/override-rules/refs/heads/main/ruleset/Crypto.list
;ruleset=⚡ Speedtest测速,https://raw.githubusercontent.com/xiaoqin24/ACL4SSR-ClashConfig/refs/heads/rm/GlobalSpeedtest.list
;ruleset=⚡ Speedtest测速,,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌🇨🇳Play下载,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 谷歌🇨🇳Play服务,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌🇨🇳Play服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 谷歌🇨🇳,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🐹 Disney+,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xiaoqin24/ACL4SSR-ClashConfig/refs/heads/rm/BrianDomainIP.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xiaoqin24/ACL4SSR-ClashConfig/refs/heads/rm/CNspeedtest.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位


  
;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://latency-test.skk.moe/endpoint`300,,50
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🛑 QUIC拦截`select`[]REJECT
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=💰 币安交易所`select`[]🇯🇵 日本节点`[]🇨🇳 台湾节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=⚡ Speedtest测速`select`[]🚀 节点选择`[]🚀 手动切换`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]DIRECT
custom_proxy_group=💬 Ai平台`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳Play下载`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳Play服务`select`[]🚀 节点选择`[]DIRECT`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌🇨🇳`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]DIRECT
custom_proxy_group=🐹 Disney+`select`[]🚀 节点选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇨🇳 台湾节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇻🇳 越南节点`[]🚀 手动切换
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
;custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
;custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇻🇳 越南节点`[]🚀 手动切换
;custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://latency-test.skk.moe/endpoint`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://latency-test.skk.moe/endpoint`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://latency-test.skk.moe/endpoint`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan)`http://latency-test.skk.moe/endpoint`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://latency-test.skk.moe/endpoint`300,,50
custom_proxy_group=🇻🇳 越南节点`url-test`(越南|Vietnam|VN)`http://latency-test.skk.moe/endpoint`300,,50
;custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://latency-test.skk.moe/endpoint`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
